### ISSUE TITLE
OnCompleted not called for disposed subscription to Observable.EveryUpdate()

### ISSUE THREAD

**Issue by bearbytes** [neuecc/UniRx#226]
This is similar to #213 

I am not sure if the behaviour is correct.
On the one hand, Observable.EveryUpdate() is a never-ending observable.
On the other hand, we might want to dispose a subscription at some time and do some cleanup in OnCompleted.

This pattern does not work:
```
IDisposable disposable;

void Start()
{
    disposable = Observable.EveryUpdate().Subscribe(DoSomething, Cleanup);
    Observable.Timer(TimeSpan.FromSeconds(2)).Subscribe(Cancel);
}

void DoSomething()
{
    // omitted
}

void Cleanup()
{
    // this is never called!
}

void Cancel()
{
    disposable.Dispose();
}
```

This pattern does work:
```
void Start()
{
    var cancellationSource = Observable.Timer(TimeSpan.FromSeconds(2));
    Observable.EveryUpdate().TakeUntil(cancellationSource).Subscribe(DoSomething, Cleanup);
}

void DoSomething()
{
    // omitted
}

void Cleanup()
{
    // now this is called
}
```

Personally, I'd expect both patterns to call OnCompleted on cancellation, but I might be argued into accepting that EveryUpdate never calls OnCompleted on its own. However, this has already led me (and probably others) into a debugging odyssey.

To "fix" the behaviour, we'd need to change `EveryCycleCore` in the following way:
```
static IEnumerator EveryCycleCore(IObserver<long> observer, CancellationToken cancellationToken)
{
    var count = 0L;
    while (!cancellationToken.IsCancellationRequested)
    {
        yield return null;
        observer.OnNext(count++);
    }
    observer.OnCompleted();
}
```

**Comment by JimW** [comment]
```
Observable
     .EveryUpdate()
     .RepeatUntilDestroy(this)
     .Subscribe(_ => { DoSomething(); }, () => { Cleanup(); });
```

If you insert RepeatUntilDestroy(this), it will call Complete when the gameobject is destroyed.  Is that good enough?

**Comment by pancomputationalist** [comment]
There are a number of potential workarounds, Since I don't have a GameObject at hand, I'm using
```
Observable.Create<long>(observer =>
{
    var d = new BooleanDisposable();
    Observable.EveryUpdate().TakeWhile(_ => !d.IsDisposed).Subscribe(observer);
    return d;
});
```
But why should a workaround even be necessary here? Is there any harm in having EveryUpdate() calling OnCompleted() on dispose, like every(?) other observable?

**Comment by JimW** [comment]
Maybe  because EveryUpdate returns a FromMicroCoroutine which is:
```
/// <summary>
 /// MicroCoroutine is lightweight, fast coroutine dispatcher.
/// IEnumerator supports only yield return null.
/// </summary>
public static IObservable<T> FromMicroCoroutine<T>(Func<IObserver<T>, CancellationToken, IEnumerator> coroutine, FrameCountType frameCountType = FrameCountType.Update)
{
      return new UniRx.Operators.FromMicroCoroutineObservable<T>(coroutine, frameCountType);
}
```
that changing EveryCycleCore as you suggested, pumping an OnComplete into FromMicroCouroutine, that it would work against (and be incompatible with) the the whole MicroCoroutine architecture and the performance gains that it brings?  I'm over my head a bit, but that's my first thought after reading "IEnumerator supports only yield return null"

**Comment by Deepscorn** [comment]
@bearbytes OnNext, OnError and OnCompleted are all semantic values pushed by source observable. You are receiving them when you are subscribed. After unsubscribing (call Dispose on Subscribtion) you don't receive anything. Why? Because you are unsubscribed.
I don't see a good reason to ruin that logic. By the way, second pattern don't receive oncompleted from source observable:
```csharp
void Start()
{
    var cancellationSource = Observable.Timer(TimeSpan.FromSeconds(2));
    Observable
      .EveryUpdate()
      .DoOnCompleted(_ = { /* not called */ })
      .TakeUntil(cancellationSource)
      .Subscribe(DoSomething, _ => { /* called because this modified observables that states that it runs until cancelationSource, when cancelationSource pushes value, modified observable returns oncompleted */ });
}
```
Did you see another implementation in rx implementation to any other language, maybe?

By the way, if you need cleanup, it is usually done that way:
For source observable:
```csharp
var observable = Observable.Create(observer =>
{
  File f = OpenFile();
  while (!f.EndOfFile()) { observer.OnNext(f.ReadLine()) }
  return Disposable.Create(() => CloseFile(f));
}
```
So, each subscriber will open file, and on unsubscribing will be cleanup. It's common pattern.

For subscriber you can use TakeUntil(closeWindowObservable/destroy/disable/pause).Subscribe(HandleNext, HandleError, CleanupIfNeeded)
