### ISSUE TITLE
IObserver<> from System.

### ISSUE THREAD

**Issue by slimshader** [neuecc/UniRx#275]
Hey,

UniRx uses IObservable from System namespace but IObserver from UniRx (is this because of IScheduler?), this causes problems when trying to integrate with other libs from System.Reactive.XXX. Ideally I'd like to be able to use F# code in my Unity projects (which is actually easy with F#kit asset) but there are conflicts due to double IObserver definitions (with the one from System.Reactive.Interfaces).

**Comment by grofit** [comment]
I believe if you are using the newer version of unirx this isnt a problem, as the internal unirx `IObservable` is within a pragma (or was) so it would get disabled if you were running in .net 4.6 (I had to work through this problem in another lib so I know at the time it was all working, but I had to use the master branch here, but I think since that the Asset Store versions been updated)
