### ISSUE TITLE
Error import UniRx 6.1.1 on asset store

### ISSUE THREAD

**Issue by vuvandong** [neuecc/UniRx#328]
[Error] The type or namespace name `IAwaiter' could not be found. Are you missing an assembly reference?
[Error] The type or namespace name `IAwaiter' could not be found. Are you missing an assembly reference?
[Error] The type or namespace name `UniTask' could not be found. Are you missing an assembly reference?
[Error] The type or namespace name `UniTask' could not be found. Are you missing an assembly reference?
[Error] The type or namespace name `UniTask' could not be found. Are you missing an assembly reference?
[Error] The type or namespace name `UniTask' could not be found. Are you missing an assembly reference?
[Error] The type or namespace name `UniTask' could not be found. Are you missing an assembly reference?
[Error] The type or namespace name `UniTask' could not be found. Are you missing an assembly reference?

**Comment by quabug** [comment]
i have same problem here after upgrade unirx from version 5.
And I think you could add ` && CSHARP_7_OR_LATER` at the end of [this line](https://github.com/neuecc/UniRx/blob/master/Assets/Plugins/UniRx/Scripts/Async/EnumeratorAsyncExtensions.cs#L1) and [this line](https://github.com/neuecc/UniRx/blob/master/Assets/Plugins/UniRx/Scripts/Async/UnityAsyncExtensions.Jobs.cs#L1) to disable whole block if you are not using incremental compiler.

This is because `UniTask` has been ignored on *regular* Unity without incremental compiler.
https://github.com/neuecc/UniRx/blob/master/Assets/Plugins/UniRx/Scripts/Async/UniTask.cs#L1

**Comment by neuecc** [comment]
Oh, sorry and thanks to reporting.
This miss is too terrible.
I'll upload new version soon...!

**Comment by neuecc** [comment]
6.1.2 was approved, maybe solved.

**Comment by vuvandong** [comment]
Problem has solved with UniRx 6.1.2.
Thanks!
