### ISSUE TITLE
debounce operator is missing?

### ISSUE THREAD

**Issue by IdeoG** [neuecc/UniRx#356]
Hello,
I'm using UniRx in my game project. You have done great work, doing this stuff. Thanks for that. My code get clear after that moment then i started to use UniRx.
But today, i beat a problem: i want to use debounce for keyboard inputs, but didn't find any implementation. 
Is there someone?

Best regargs,
Alex

**Comment by KAW0** [comment]
Use "Throttle" operator. http://reactivex.io/documentation/operators/debounce.html

**Comment by IdeoG** [comment]
> Use "Throttle" operator. http://reactivex.io/documentation/operators/debounce.html

"Throttle" operator doesn't handle the issue. Here, i apply pseudo-code what i expect to see:
```
this.UpdateAsObservable()
    .Where(_ => Input.GetKey(KeyCode.A))
    .Debounce(500)
    .Subscribe(_ =>OnKeyPressedDown());
```
Then i press down A - button, method `OnKeyPressedDown` is called every 500 ms. But then i use `Throttle` i get another behaviour, because this operator brings another functionality (`OnKeyPressedDown` is called after 500 ms, after i get key up).

**Comment by SugoiDev** [comment]
Here's a nice explanation of the differences between those two: https://css-tricks.com/the-difference-between-throttling-and-debouncing/

**Comment by IdeoG** [comment]
Debounce is exactly what i want, don't call function untill some time has expired

**Comment by IdeoG** [comment]
Anyway i have already implemented some tricky solution.

**Comment by southrop** [comment]
This library probably lacks a `Debounce` operator because [Rx.NET](/dotnet/reactive) does not have one, and this is simply a re-implementation for Unity.

But to add to the confusion, it turns out Rx.NET actually implements the [`Debounce`](http://rxmarbles.com/#debounce) operator behaviour as `Throttle`, and does not have a real [`Throttle`](http://rxmarbles.com/#throttle) operator (see dotnet/reactive#395). To clarify, `Throttle` emits an item when it receives an item, but it will not emit any more items until a defined timespan has passed since the last received item. On the other hand, `Debounce` emits a value after a defined timespan has passed since the last received item.

Which means that in @IdeoG's case, the
> `OnKeyPressedDown` is called after 500 ms, after i get key up

behaviour you describe is the real `Debounce` behaviour, and what you wanted is actually `Throttle`.

**Comment by Thaina** [comment]
Sorry for the digging old thread but now I am curious what is equivalence implementation of `Throttle` in `unirx` of the `System.Reactive` then?
