### ISSUE TITLE
Observable WhenAll / Zip issues

### ISSUE THREAD

**Issue by Tostifrosti** [neuecc/UniRx#368]
I'm having issues with your library in a certain scenario.
I have a list that contains multiple `ObservableWWW`. They all need to load a small package of some KB over HTTP. I'm using `Observable.WhenAll` or `Observable.Zip` to subscribe for when all these requests are done. 

The problem that I am encountering is that these 2 methods are trying to load everything at once. This will produce several Http errors because you can have only a handful of Http requests at the same time.

Would it be a good idea to have a parameter in those 2 methods that will tell on how many observables it can load at the same time. (this might also remove some stress for the servers)

Thanks in advance!

**Comment by MystikalPooka** [comment]
That should be expected behavior for WhenAll... The entire point of it is to subscribe to all sequences at once, then return completed when all sequences complete.

If you need to only do a couple at a time try Concat (sequentially run sub sequences until they all complete) or try using an interval and a buffer to only do a few at a time through WhenAll.
